// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GetSettingsEvent } from "./GetSettingsEvent";
import type { KeyExpiryEvent } from "./KeyExpiryEvent";
import type { KeyResumeEvent } from "./KeyResumeEvent";
import type { SettingExecuteEvent } from "./SettingExecuteEvent";

export type AntiraidEvent = { "KeyExpiry": KeyExpiryEvent } | { "KeyResume": KeyResumeEvent } | { "GetSettings": GetSettingsEvent } | { "ExecuteSetting": SettingExecuteEvent };
