// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiCreateCommandOptionChoice } from "./ApiCreateCommandOptionChoice";

/**
 * Publicly accessible representation of a Discord command option
 */
export type ApiCreateCommandOption = { type: number, name: string, name_localizations: { [key in string]?: string } | null, description: string, description_localizations: { [key in string]?: string } | null, required: boolean, choices: Array<ApiCreateCommandOptionChoice>, options: Array<ApiCreateCommandOption>, channel_types: number, min_value: number | null, max_value: number | null, min_length: number | null, max_length: number | null, autocomplete: boolean, };
