// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from './serde_json/JsonValue';

/**
 * Represents a choice for a command option
 */
export type ApiCreateCommandOptionChoice = {
	name: string;
	name_localizations: { [key in string]?: string } | null;
	value: JsonValue;
};
