// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiConfig = {
	/**
	 * The ID of the main AntiRaid support server
	 */
	main_server: string;
	/**
	 * Discord Support Server Link
	 */
	support_server_invite: string;
	/**
	 * The ID of the AntiRaid bot client
	 */
	client_id: string;
};
