// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiDispatchResult<T> = { "type": "Ok", "data": T } | { "type": "Err", "data": string };
