// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiLuaVmResult } from "./ApiLuaVmResult";

export type ApiLuaVmResultHandle = { result: ApiLuaVmResult, template_name: string, };
