// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An action that can be performed on the Lua VM
 */
export type ApiLuaVmAction =
	| { Stop: Record<string, never> }
	| { GetMemoryUsage: Record<string, never> }
	| { SetMemoryLimit: { limit: number } }
	| { ClearCache: Record<string, never> }
	| { Panic: Record<string, never> };
