// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type ApiLuaVmResult = { "Ok": { result: JsonValue, } } | { "LuaError": { err: string, } } | { "VmBroken": Record<string, never> };
