// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiPartialRole = { 
/**
 * The ID of the role
 */
id: string, 
/**
 * The name of the role
 */
name: string, 
/**
 * The position of the role in the guild
 */
position: number, 
/**
 * Permissions of the role
 */
permissions: string, };
