// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiPartialGuildChannel = {
	/**
	 * The ID of the channel
	 */
	id: string;
	/**
	 * The name of the channel
	 */
	name: string;
	/**
	 * The position of the channel in the guild
	 */
	position: number;
	/**
	 * The ID of the parent channel, if any
	 */
	parent_id: string | null;
	/**
	 * The type of the channel
	 */
	type: number;
};
