// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiThreadGuildVmMetrics } from './ApiThreadGuildVmMetrics';

export type ApiThreadMetrics = {
	/**
	 * Metrics for each guild
	 */
	vm_metrics: { [key in string]?: ApiThreadGuildVmMetrics };
	/**
	 * The thread ID
	 */
	tid: number;
};
