// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single thread's clear inactive guilds response
 */
export type ApiThreadClearInactiveGuilds = {
	tid: number;
	cleared: { [key in string]?: string | null };
};
