// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiThreadGuildVmMetrics = {
	/**
	 * Used memory
	 */
	used_memory: number;
	/**
	 * Memory limit for the Luau VM
	 */
	memory_limit: number;
	/**
	 * Number of luau threads
	 */
	num_threads: number;
	/**
	 * Maximum luau threads
	 */
	max_threads: number;
};
