// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents an authorized session and its associated user
 *
 * Note: this is *very* different from a UserSession and provides different/limited data
 */
export type AuthorizedSession = {
	/**
	 * User ID
	 */
	user_id: string;
	/**
	 * Session ID
	 */
	id: string;
	/**
	 * The state of the user
	 */
	state: string;
	/**
	 * The type of session
	 */
	type: string;
};
