// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiPartialRole } from './ApiPartialRole';
import type { GuildChannelWithPermissions } from './GuildChannelWithPermissions';

export type BaseGuildUserInfo = {
	owner_id: string;
	name: string;
	icon: string | null;
	/**
	 * List of all roles in the server
	 */
	roles: Array<ApiPartialRole>;
	/**
	 * List of roles the user has
	 */
	user_roles: Array<string>;
	/**
	 * List of roles the bot has
	 */
	bot_roles: Array<string>;
	/**
	 * List of all channels in the server
	 */
	channels: Array<GuildChannelWithPermissions>;
};
