// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InnerColumnType } from './InnerColumnType';
import type { InnerWidget } from './InnerWidget';

export type ColumnType =
	| {
			type: 'Scalar';
			/**
			 * The value type
			 */
			inner: InnerColumnType;
	  }
	| {
			type: 'Array';
			/**
			 * The inner type of the array
			 */
			inner: InnerColumnType;
	  }
	| {
			type: 'Widget';
			/**
			 * The inner widget type
			 */
			inner: InnerWidget;
	  };
