// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnType } from './ColumnType';

export type Column = {
	/**
	 * The ID of the column on the database
	 */
	id: string;
	/**
	 * The friendly name of the column
	 */
	name: string;
	/**
	 * The description of the column
	 */
	description: string;
	/**
	 * Placeholder text for the column, used in the UI
	 */
	placeholder: string | null;
	/**
	 * The type of the column
	 */
	column_type: ColumnType;
	/**
	 * Whether or not the column is a primary key
	 */
	primary_key: boolean;
	/**
	 * Whether or not the column is nullable
	 */
	nullable: boolean;
	/**
	 * Whether the field should be hidden for the given operations
	 */
	hidden: Array<string>;
	/**
	 * Whether the field is readonly for the given operations. Readonly fields may or may not be sent to the server
	 */
	readonly: Array<string>;
};
