// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Create a API user session
 */
export type CreateUserSession = { name: string, type: string, expiry: number, };
