// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DashboardGuild } from './DashboardGuild';

export type DashboardGuildData = { guilds: Array<DashboardGuild>; bot_in_guilds: Array<string> };
