// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query parameters for dispatch_event_and_wait
 */
export type DispatchEventAndWaitQuery = {
	/**
	 * Wait duration in milliseconds
	 */
	wait_timeout: number | undefined;
};
