// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Footer = {
	/**
	 * The text to display in the footer of the setting as a whole
	 */
	end_text: string;
};
