// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShardConn } from './ShardConn';

/**
 * A response containing the status of all shards
 */
export type GetStatusResponse = {
	/**
	 * A map of shard group ID to shard connection information
	 */
	shard_conns: { [key in number]?: ShardConn };
	/**
	 * The total number of guilds the bot is connected to
	 */
	total_guilds: number;
	/**
	 * The total number of users
	 */
	total_users: number;
};
