// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiPartialGuildChannel } from "./ApiPartialGuildChannel";

export type GuildChannelWithPermissions = { 
/**
 * User permissions
 */
user: string, 
/**
 * Bot permissions
 */
bot: string, 
/**
 * Channel data
 */
channel: ApiPartialGuildChannel, };
