// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Note: this is merely a hint used for styling the website
 */
export type InnerWidget =
	| {
			type: 'Info';
			/**
			 * The info message to display
			 */
			message: string;
	  }
	| {
			type: 'Warning';
			/**
			 * The warning message to display
			 */
			message: string;
	  }
	| {
			type: 'Button';
			/**
			 * The label of the button
			 */
			label: string;
			/**
			 * The operation to perform when the button is clicked
			 */
			op: string;
	  };
