// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Note: this is merely a hint used for styling the website
 */
export type InnerColumnType = { "type": "String", min_length: number | null, max_length: number | null, allowed_values: Array<string>, suggestions: Array<string> | null, kind: string, } | { "type": "Integer", } | { "type": "Float", } | { "type": "BitFlag", 
/**
 * The bit flag values
 */
values: { [key in string]?: bigint }, } | { "type": "Boolean", } | { "type": "Json", style: string, };
