// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The PartialUser of a user, which contains only the necessary fields for the API
 */
export type PartialUser = { 
/**
 * The ID of the user
 */
id: string, 
/**
 * The username of the user
 */
username: string, 
/**
 * The global name of the user
 */
global_name: string | null, 
/**
 * The avatar hash of the user
 */
avatar: string | null, };
