// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from './serde_json/JsonValue';

export type SettingExecuteEvent = {
	/**
	 * The ID of the setting being executed
	 */
	id: string;
	/**
	 * The author of the event
	 */
	author: string;
	/**
	 * The operation being performed on the setting
	 */
	op: string;
	/**
	 * The fields of the operation. May be a map or list of fields
	 */
	fields: JsonValue;
};
