// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiCreateCommand } from './ApiCreateCommand';

export type TwState = { commands: Array<ApiCreateCommand> };
