// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserSession } from './UserSession';

export type UserSessionList = {
	/**
	 * The list of user sessions
	 */
	sessions: Array<UserSession>;
};
